.\"
.\" scp.1
.\"
.\" Author: Tatu Ylonen <ylo@cs.hut.fi>
.\"
.\" Copyright (c) 1995 Tatu Ylonen <ylo@cs.hut.fi>, Espoo, Finland
.\"                    All rights reserved
.\"
.\" Created: Sun May  7 00:14:37 1995 ylo
.\"
.\" $OpenBSD: scp.1,v 1.71 2016/07/16 06:57:55 jmc Exp $
.\"
.\" Japanese translation by Yusuke Shinyama <yusuke at cs . nyu . edu>
.\"
.Dd $Mdocdate: July 16 2016 $
.Dt SCP 1
.Os
.Sh 名前
.Nm scp
.Nd 安全なファイルコピー (リモート ファイルコピー プログラム)
.Sh 書式
.Nm scp
.Bk -words
.Op Fl 12346BCpqrv
.Op Fl c Ar 暗号方式
.Op Fl F Ar ssh設定ファイル
.Op Fl i Ar identityファイル
.Op Fl l Ar 帯域制限
.Op Fl o Ar ssh設定項目
.Op Fl P Ar ポート番号
.Op Fl S Ar プログラム
.Sm off
.Oo
.Op Ar ユーザ No @
.Ar ホスト1 :
.Oc Ar ファイル1
.Sm on
.Ar ...
.Sm off
.Oo
.Op Ar ユーザ No @
.Ar ホスト2 :
.Oc Ar ファイル2
.Sm on
.Ek
.Sh 説明
.Nm
はネットワーク上のホスト間でファイルをコピーします。
これはデータ転送に 
.Xr ssh 1
を使い、これと同様の認証をおこないます。これによって、
.Xr ssh 1
と同様のセキュリティを提供します。
.Nm
は認証に必要な場合、パスワードまたはパスフレーズを尋ねてきます。
.Pp
各ファイル名には、ホストおよびユーザの指定を含めることができます。これは
そのファイルがどのホストから、あるいはどのホストにコピーされるかを
指定するものです。ローカルなファイル名は、
.Sq :\&
を含む名前を
.Nm
がホスト指定と混同しないように、
絶対パス名または相対パス名を使ってください。
2つのリモートホスト間でファイルコピーすることもできます。
.Pp
オプションは次のとおりです:
.Bl -tag -width Ds
.It Fl 1
.Nm
がプロトコル 1 を使うよう強制します。
.It Fl 2
.Nm
がプロトコル 2 を使うよう強制します。
.It Fl 3
ローカルホストを経由して、2つのリモートホスト間でコピーをおこないます。
このオプションが指定されない場合、データは2つのリモートホスト間でじかにコピーされます。
注意: このオプションを使うと、進行状況の表示はされません。
.It Fl 4
.Nm
が IPv4 アドレスのみを使うよう強制します。
.It Fl 6
.Nm
が IPv6 アドレスのみを使うよう強制します。
.It Fl B
バッチ処理モード (パスワードやパスフレーズを尋ねないようにします)。
.It Fl C
通信を圧縮します。
.Xr ssh 1
に
.Fl C
フラグを渡して圧縮を許可します。
.It Fl c Ar 暗号方式
データ転送に使う暗号方式を選択します。このオプションは直接
.Xr ssh 1
に渡されます。
.It Fl F Ar ssh設定ファイル
.Nm ssh
に対して別のユーザ設定ファイルを指定します。
このオプションは直接
.Xr ssh 1
に渡されます。
.It Fl i Ar identityファイル
公開鍵認証用の秘密鍵を読むファイルを選択します。
このオプションは直接
.Xr ssh 1
に渡されます。
.It Fl l Ar limit
使われるネットワーク帯域を制限します。Kbit/s で指定します。
.It Fl o Ar ssh設定項目
設定ファイル
.Xr ssh_config 5
で使われている形式のオプションを
.Nm ssh
に渡すために使います。
これは 
.Nm scp
のコマンドラインオプションからは直接指定できない
項目を指定するときに便利です。
以下のオプションの詳細と、これらがとりうる値については
.Xr ssh_config 5
を参照してください。
.Pp
.Bl -tag -width Ds -offset indent -compact
.It AddressFamily
.It BatchMode
.It BindAddress
.It CanonicalDomains
.It CanonicalizeFallbackLocal
.It CanonicalizeHostname
.It CanonicalizeMaxDots
.It CanonicalizePermittedCNAMEs
.It CertificateFile
.It ChallengeResponseAuthentication
.It CheckHostIP
.It Cipher
.It Ciphers
.It Compression
.It CompressionLevel
.It ConnectionAttempts
.It ConnectTimeout
.It ControlMaster
.It ControlPath
.It ControlPersist
.It GlobalKnownHostsFile
.It GSSAPIAuthentication
.It GSSAPIDelegateCredentials
.It HashKnownHosts
.It Host
.It HostbasedAuthentication
.It HostbasedKeyTypes
.It HostKeyAlgorithms
.It HostKeyAlias
.It HostName
.It IdentitiesOnly
.It IdentityAgent
.It IdentityFile
.It IPQoS
.It KbdInteractiveAuthentication
.It KbdInteractiveDevices
.It KexAlgorithms
.It LogLevel
.It MACs
.It NoHostAuthenticationForLocalhost
.It NumberOfPasswordPrompts
.It PasswordAuthentication
.It PKCS11Provider
.It Port
.It PreferredAuthentications
.It Protocol
.It ProxyCommand
.It ProxyJump
.It PubkeyAcceptedKeyTypes
.It PubkeyAuthentication
.It RekeyLimit
.It RhostsRSAAuthentication
.It RSAAuthentication
.It SendEnv
.It ServerAliveInterval
.It ServerAliveCountMax
.It StrictHostKeyChecking
.It TCPKeepAlive
.It UpdateHostKeys
.It UsePrivilegedPort
.It User
.It UserKnownHostsFile
.It VerifyHostKeyDNS
.El
.It Fl P Ar ポート番号
リモートホストに接続するポート番号を指定します。
このオプションは大文字の
.Sq P
であることに注意してください。これは小文字の
.Fl p
が、時刻やパーミッションを保つオプションとして
すでに使われているためです。
.It Fl p
コピー元ファイルの最終修正時刻、最終アクセス時刻、および
パーミッションを保つようにします。
.It Fl q
沈黙モード。
.Xr ssh 1
が進行状況を表すメータや警告および診断メッセージを
表示しないようにします。
.It Fl r
ディレクトリ全体を再帰的にコピーします。
.Nm
は遭遇したシンボリック・リンクを追いますので注意してください。
.It Fl S Ar プログラム
暗号化された接続のために使う
.Ar プログラム
の名前を指定します。このプログラムは
.Xr ssh 1
のオプションが使用できなくてはいけません。
.It Fl v
冗長表示モード。
.Nm
と
.Xr ssh 1
が進行中のデバッグメッセージを表示するようにします。
これは接続や認証、設定の問題などをデバッグするときに役立ちます。
.El
.Sh 終了状態
.Ex -std scp
.Sh 関連項目
.Xr sftp 1 ,
.Xr ssh 1 ,
.Xr ssh-add 1 ,
.Xr ssh-agent 1 ,
.Xr ssh-keygen 1 ,
.Xr ssh_config 5 ,
.Xr sshd 8
.Sh 歴史
.Nm
は、カリフォルニア州立大学評議会 (the Regents of the University of
California) による
.Bx
ソースコードの rcp を基にしています。
.Sh 作者
.An Timo Rinne Aq Mt tri@iki.fi
.An Tatu Ylonen Aq Mt ylo@cs.hut.fi
