.\" $OpenBSD: sftp-server.8,v 1.19 2010/01/09 03:36:00 jmc Exp $
.\"
.\" Copyright (c) 2000 Markus Friedl.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" Japanese translation: $Id$
.\" by Yusuke Shinyama <yusuke at cs . nyu . edu>
.\"
.Dd $Mdocdate: January 9 2010 $
.Dt SFTP-SERVER 8
.Os
.Sh 名前
.Nm sftp-server
.Nd SFTP サーバ サブシステム
.Sh 書式
.Nm sftp-server
.Op Fl ehR
.Op Fl f Ar ログ出力先
.Op Fl l Ar ログレベル
.Op Fl u Ar umask
.Sh 説明
.Nm
はサーバ側の SFTP プロトコルを標準出力に向かって話し、
クライアント側の要求を標準入力から受けつけます。
.Nm
は直接 実行されるためにあるのではなく、
.Xr sshd 8
の
.Cm Subsystem
オプションを使って呼び出します。
.Pp
.Nm
へのコマンドラインオプションは
.Cm Subsystem
宣言によって指定されます。
より詳しい情報については
.Xr sshd_config 5
を見てください。
.Pp
使用できるオプションは以下のとおりです:
.Bl -tag -width Ds
.It Fl e
デバッグのために、
.Nm
のログを syslog ではなく標準エラー出力に表示します。
.It Fl f Ar ログ出力先
.Nm
のログメッセージ出力先 (facility) を指定します。
指定できる値は: DAEMON, USER, AUTH, LOCAL0, LOCAL1, LOCAL2,
LOCAL3, LOCAL4, LOCAL5, LOCAL6, LOCAL7
のどれかです。デフォルトは AUTH です。
.It Fl h
.Nm
の使用法を表示します。
.It Fl l Ar ログレベル
.Nm
が表示するどのログメッセージを記録するかを指定します。
指定できる値は:
QUIET, FATAL, ERROR, INFO, VERBOSE, DEBUG, DEBUG1, DEBUG2, 
および DEBUG3 のどれかです。
INFO および VERBOSE は
.Nm
がクライアントのために実行した操作を記録します。
DEBUG および DEBUG1 は等価です。
DEBUG2 および DEBUG3 はそれぞれさらに高いレベルのデバッグ情報を残します。
デフォルトの値は ERROR です。
.It Fl R
この
.Nm
インスタンスを読み込み専用 (read-only) モードにします。
ファイルへの書き込みや、その他ファイルシステムの状態を変更する操作は
すべて拒否されます。
.It Fl u Ar umask
新しく作られるファイルに対して、明示的に
.Xr umask 2
の値を指定します。これはユーザのデフォルト umask 値のかわりに使われます。
.El
.Pp
ログをとるためには、
.Nm
が
.Pa /dev/log 
にアクセスできるようになっている必要があります。
したがって、chroot 環境下で
.Nm
を使うには
.Xr syslogd 8
が chroot ディレクトリ内にログ用ソケットを用意するよう設定する必要があります。
.Sh 関連項目
.Xr sftp 1 ,
.Xr ssh 1 ,
.Xr sshd_config 5 ,
.Xr sshd 8
.Rs
.%A T. Ylonen
.%A S. Lehtinen
.%T "SSH File Transfer Protocol"
.%N draft-ietf-secsh-filexfer-00.txt
.%D January 2001
.%O work in progress material
.Re
.Sh 歴史
.Nm
は
OpenBSD 2.8
で最初に登場しました。
.Sh 作者
.An Markus Friedl Aq markus@openbsd.org
